global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'node01'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['bc-exporter-01:9091']
  - job_name: 'node02'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['bc-exporter-01:9092']
  - job_name: 'node03'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['bc-exporter-01:9093']

